server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:~/fiapcervejaria;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    user:
      name: admin
      password: fiap
      roles: ADMIN

jwt:
  secret: F14ps3cr3t
  expiration: 1